# Generated by Django 5.1.4 on 2025-01-05 21:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mascota_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
