# Generated by Django 5.1.4 on 2025-01-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_slug_alter_producto_imagen'),
        ('api', '0005_alter_mascota_id'),
    ]

    operations = [
    ]
