# Generated by Django 5.1.4 on 2025-01-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250106_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
