# Generated by Django 5.1.4 on 2025-01-06 21:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250106_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='imagen',
        ),
        migrations.AddField(
            model_name='mascota',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
