# Generated by Django 5.1.4 on 2025-01-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_mascota_imagen_mascota_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='image',
            new_name='imagen',
        ),
    ]
