# Generated by Django 5.1.4 on 2025-01-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_producto_ingredientes_alter_producto_imagen'),
        ('api', '0009_alter_producto_imagen'),
    ]

    operations = [
    ]
