# Generated by Django 5.1.4 on 2025-01-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, null=True),
        ),
    ]
