# Generated by Django 5.1.4 on 2025-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_mascota_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='titulo',
            field=models.CharField(default='Sin titulo', max_length=255),
        ),
    ]
