# Generated by Django 5.1.4 on 2025-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_resena_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
