# Generated by Django 5.1.4 on 2025-01-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Preparación', 'Preparación'), ('Entregado', 'Entregado'), ('Transito', 'Transito'), ('Cancelado', 'Cancelado')], default='Preparación', max_length=255),
        ),
    ]
