# Generated by Django 5.1.4 on 2025-01-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionadopcion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
