# Generated by Django 5.1.4 on 2025-01-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_publicacionadopcion_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionadopcion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
