# Generated by Django 5.1.4 on 2025-01-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_direccion_localidad_alter_user_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
