# Generated by Django 5.1.4 on 2025-01-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_direccion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionadopcion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='publicacionadopcion',
            name='direccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
    ]
