# Generated by Django 5.1.4 on 2025-01-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_direccion_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='localidad',
            constraint=models.CheckConstraint(condition=models.Q(('nombre__gt', '')), name='nombre_no_vacio'),
        ),
    ]
