# Generated by Django 5.1.4 on 2025-01-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_localidad_nombre_no_vacio'),
        ('api', '0025_remove_publicacionadopcion_ubicacion_and_more'),
    ]

    operations = [
    ]
