# Generated by Django 5.1.4 on 2025-01-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto_ninos', models.BooleanField(default=False)),
                ('apto_ruido', models.BooleanField(default=False)),
                ('espacio', models.CharField(choices=[('P', 'Pequeño'), ('G', 'Grande')], max_length=255)),
                ('apto_otras_mascotas', models.BooleanField(default=False)),
                ('desparacitado', models.BooleanField(default=False)),
                ('vacunado', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.mascota')),
            ],
        ),
    ]
