# Generated by Django 5.1.4 on 2025-01-14 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20250114_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.localidad'),
        ),
    ]
