# Generated by Django 5.1.4 on 2025-01-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_direccion_localidad'),
        ('api', '0027_detallemascota'),
    ]

    operations = [
    ]
