# Generated by Django 5.1.4 on 2025-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_detallemascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=255, null=True),
        ),
    ]
