# Generated by Django 5.1.4 on 2025-01-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_categoriaprincipal_categoria_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionadopcion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
