# Generated by Django 5.1.4 on 2025-01-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_publicacionadopcion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallemascota',
            old_name='desparacitado',
            new_name='desparasitado',
        ),
    ]
