# Generated by Django 5.1.4 on 2025-02-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_desparacitado_detallemascota_desparasitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
