# Generated by Django 5.1.4 on 2025-02-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_user_saldo'),
        ('api', '0032_alter_solicitudadopcion_fecha'),
    ]

    operations = [
    ]
