# Generated by Django 5.1.4 on 2025-02-02 21:48

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20250202_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='descripcion_servicio',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cuidador',
            name='categoriaMascotas',
            field=models.CharField(blank=True, choices=[('Gatos', 'Gatos'), ('Perros', 'Perros'), ('Aves', 'Aves'), ('Reptiles', 'Reptiles'), ('Roedores', 'Roedores'), ('Peces', 'Peces')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.localidad'),
        ),
    ]
