# Generated by Django 5.1.4 on 2025-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_cuidador_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
