# Generated by Django 5.1.4 on 2025-02-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_resena_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resena',
            old_name='likes',
            new_name='num_likes',
        ),
    ]
