# Generated by Django 5.1.4 on 2025-02-17 16:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_likes_resena_num_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='hoja_vida',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
