# Generated by Django 5.1.4 on 2025-02-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cuidador_hoja_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidado',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitudcuidado',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
