# Generated by Django 5.1.4 on 2025-02-17 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_solicitudcuidado_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcuidado',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
