# Generated by Django 5.1.4 on 2025-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_solicitudcuidado_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidado',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
