# Generated by Django 5.1.4 on 2025-02-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_solicitudcuidado_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcuidado',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
