# Generated by Django 5.1.4 on 2025-02-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_solicitudcuidado_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcuidado',
            name='horas_cuidado',
            field=models.IntegerField(default=0),
        ),
    ]
