# Generated by Django 5.1.4 on 2025-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_solicitudcuidado_horas_cuidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcuidado',
            name='is_cuidado_especial',
            field=models.BooleanField(default=False),
        ),
    ]
