# Generated by Django 5.1.4 on 2025-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_solicitudcuidado_is_cuidado_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidado',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=255),
        ),
    ]
