# Generated by Django 5.1.4 on 2025-02-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_solicitudcuidado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='cedula',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
