# Generated by Django 5.1.4 on 2025-02-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_cuidador_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuidador',
            old_name='categoriaMascotas',
            new_name='categoria_mascotas',
        ),
    ]
