# Generated by Django 5.1.4 on 2025-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_rename_categoriamascotas_cuidador_categoria_mascotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='cedula',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
