# Generated by Django 5.1.4 on 2025-02-19 17:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_cuidador_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='cedula',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='hoja_vida',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hoja_vida'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
