# Generated by Django 5.1.4 on 2025-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_cuidador_cedula_alter_cuidador_hoja_vida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
