# Generated by Django 5.1.4 on 2025-02-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_cuidador_email_cuidador_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcuidado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
